spring.application.name=compagnie_aerienne


spring.datasource.url=jdbc:postgresql://localhost:5432/compagnie_aerienne
spring.datasource.username=noraa
spring.datasource.password=noraa
spring.datasource.driver-class-name=org.postgresql.Driver